name: 'Commit Format QA'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout main branch'
        uses: actions/checkout@v3

      - name: 'Setup Node v18'
        uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'yarn'

      - name: Install deps from 'yarn.lock'
        run: yarn install --frozen-lockfile

      - name: 'Check formatting'
        run: yarn run format:check
